"""add_user_id_to_test_runs

Revision ID: 8f22856dc35f
Revises: cf9a13064c12
Create Date: 2026-01-06 11:12:50.385556

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f22856dc35f'
down_revision: Union[str, None] = 'cf9a13064c12'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Clean up any leftover temporary tables from previous migrations
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    existing_tables = inspector.get_table_names()
    if '_alembic_tmp_test_runs' in existing_tables:
        op.drop_table('_alembic_tmp_test_runs')
    
    # Check if user_id column already exists
    existing_columns = [col['name'] for col in inspector.get_columns('test_runs')]
    if 'user_id' not in existing_columns:
        # Only add user_id to test_runs table if it doesn't exist
        with op.batch_alter_table('test_runs', schema=None, recreate='always', naming_convention={
            "fk": "fk_%(table_name)s_%(column_0_name)s"
        }) as batch_op:
            batch_op.add_column(sa.Column('user_id', sa.String(length=36), nullable=True))
            batch_op.create_index(batch_op.f('ix_test_runs_user_id'), ['user_id'], unique=False)
            batch_op.create_foreign_key('fk_test_runs_user_id', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Remove user_id from test_runs table
    with op.batch_alter_table('test_runs', schema=None) as batch_op:
        batch_op.drop_constraint('fk_test_runs_user_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_test_runs_user_id'))
        batch_op.drop_column('user_id')
    # ### end Alembic commands ###
